### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by claudiamig** [claudiamig/closer-to-the-sky#4]
# Roadmap
*Co-creating astronomical knowledge in favelas in Rio de Janeiro*

Closer to the Sky is an astronomy outreach project building a bridge between favelas (slums) of Rio de Janeiro and universities/research centers via a mutual enriching approach. Science dissemination and education are brought into the favela while people of the favela are invited to co-create scientific content in collaboration with students, researchers and professors. This approach promotes inclusion, values community knowledge and culture, and provides institutional support and protection to these fragile contexts.

## What do we need to do?

To achieve our goals, we need to:
* Create educational material with a decolonized vision of science
* Implement the course in the community
* Train astro-guides and engage artists
* Obtain funds to support contributors

### Milestone: Educational resources 📚

* Enriching the library
- [x] Compile a list of books to purchase (thanks to IAU OAD project [OruMbya: a library of silenced voices](https://www.astro4dev.org/orumbya-library-of-silenced-voices/))
- [x] Compile a list of digital resources to print
- [ ] Translate digital resources if not available in portuguese
- [ ] Create our own course material and print it in the form of a booklet - see ➡💫

> We plan to reach this milestone by December 2023

* Creating our booklet 💫
- [x] Compile course syllabus
- [ ] Create a pilot unit
- [ ] Evaluate pilot unit during course
- [ ] Improve pilot unit
> We plan to reach this sub-milestone by July 2023

- [ ] Repeat as above with other units
- [ ] Finalise version 1.0 of booklet
- [ ] Compile resources into printing layout
- [ ] Print booklet
> We plan to reach this milestone by June 2024

- [ ] Publish version 1.0 of booklet online as open source
- [ ] Translate version 1.0 of booklet into other languages
- [ ] Keep iterating on future version of the booklet with project users and contributors
> We plan to reach this milestone by early 2024

### Milestone: Course implementation 🌞
- [ ] Implement weekly course for teenagers
- [x] Implement weekly course for younger children
- [ ] Evaluation
- [ ] Publish course documentation online

> We plan to reach this milestone by December 2023

### Milestone: Training Astro-guides 🔭

- [x] Connect with AstroTribes project in Pune (India)
- [ ] Set out regular meetings with AstroTribes
- [ ] Organise practical observation sessions with telescopes
- [ ] Design uniforms
- [ ] Create uniforms

> We plan to reach this milestone by mid 2024

### Milestone: Collaboration with local artists 🌈
 
- [ ] Partecipate at the IAU OAO project The Art of Astronomy (https://iaunocbrasil4.wixsite.com/a-arte-da-astronomia/como-participar)
- [ ] Promote the course and project in the favela
- [ ] Invite local artists to join the project as contributors (class tutors)

> Note: The OAO project deadline is June 30 (probably extended). 
> We plan to finalize this milestone by early 2024 
> Note: This milestone depends on obtaining funds - see ➡💰

### Milestone: Fundraising 💰

- [x] Identify potential funding bodies
- [x] Write proposal, apply
- [ ] Obtain funds
- [ ] Once funding available: engage local artists to contribute to the course as tutors
- [ ] Once funding available: offer compensation for astro-guides

> We plan to reach this milestone by end of 2023 / early 2024
